version: '3.4'
services:
  mysql:
    container_name: container_nxtmysql
    image: nxtmysql:0.1.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nxtframework
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    # command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
