version: '3.4'
services:
  autoheal:
    container_name: autoheal_newxton_super_company_api
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  springboot:
    container_name: springboot_newxton_super_company_api
    image: newxton_super_company_api:0.0.1
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    restart: always
  nginx:
    container_name: nginx_newxton_super_company_api
    image: nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./http/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./http/ssl_cert.key:/ssl_cert.key:ro
      - ./http/ssl_cert.pem:/ssl_cert.pem:ro
    restart: always