version: '3.4'
services:
  autoheal:
    container_name: autoheal_newxton_companywebsite_api
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  springboot_newxton_companywebsite_server:
    container_name: container_newxton_companywebsite_api
    image: newxton_companywebsite_api:0.0.1
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    restart: always
