version: '3.4'
services:
  autoheal:
    container_name: autoheal_newxton_super_company_api
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  springboot:
    container_name: springboot_newxton_super_company_api
    image: newxton_super_company_api:0.0.1
    ports:
      - target: 8080
        published: 8081
        protocol: tcp
        mode: host
    restart: always